### PR TITLE
[launching] add BndContainerRuntimeClasspathEntryResolver

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by bjhargrave** [comment]
Basically it looks ok to me but I don't have any understanding of this part of Eclipse :-)

**Comment by bjhargrave** [comment]
@gamerson, should we go ahead and merge this?

**Comment by gamerson** [comment]
Sorry I haven't gotten a chance to test it fully, on all Bnd launch types (like bndrun launches, etc).  I hope to have a chance to test it this week, before Friday.

**Comment by gamerson** [comment]
hey @bjhargrave I have confirmed that this new resolver introduces issues in other types of bnd launches, so I will close this for now until I can take another look at the implementation.

**Pull request closed without merging**
