### PR TITLE
#1412: Split ProjectRunPage into multiple pages and add a icon for Runtime page

### PR DESCRIPTION
**Pull request by wodencafe**
Hi guys, here is the PR for the code changes of issue #1412
:)

### CODE REVIEW

**Comment by gamerson** [comment]
@wodencafe thanks for you willingness to help out with this fairly complex UI.  But since we are on the topic of this UI, why not try to take our changes a bit further to group related things together.  Would you be wiling to do a little more UI improvement?

It seems that there are two categories of UI widgets here.  Those related to `resolving` and those related to `Running or launching` the osgi runtime

`Resolving` related widgets are
1. Repos (select which repos will be considered when resolving)
2. Browse repos (select from this and drag-drop them to Run Requires, Run Blacklist, Run Bundles)
3. Run requirements 
4. Run blacklist
5. Run bundles

`Running or launching` related widgets are
1. Core Runtime
2. OSGi Framework properties
3. Launcher arguments
4. VM arguments


So here is my proposal.

new bndrun editor ui pages

I've attached the balsamiq mockup sources here if anyone wants to edit this (used Balsamiq Mockups 3.5.7)
[NewBndRunEditor.zip](https://github.com/bndtools/bndtools/files/755807/NewBndRunEditor.zip)

**Comment by wodencafe** [comment]
Hi @bjhargrave , I will update my commit messages to include the signed off message tonight.
Hi @gamerson, these are great suggestions! I would certainly be willing to implement these changes, let me see what I can come up with tonight.

**Comment by pkriens** [comment]
I like this work! Suggestion:

First tab: [Input to the Resolver] 
   Distro
   System capabilities/packages [extra]
   Framework
   EE
   Repository selection

Second tab [ Resolver ]
   Possible requirements from the repositories
   Run Requirements
   Black list

Third tab [Resolver results]
  Run bundles
  Add a repository list so it can be manually edited
  run properties, vm args, program args

**Comment by gamerson** [comment]
Hey @pkriens  is a new mockup UI based on the new requirements we discussed last week.  I'd like to hear from other committers on this new UI before @wodencafe begins to update his PR.

new bndrun editor

**Comment by pkriens** [comment]
Nice work but you've opened the gates :-) I did some checking of what kind of options we have and I've made a completely new mockup. Might be too much work but it should at least give ideas

First, a central part seems to be a resource browser view. It would be nice if we had this stand alone but I think it is important to use in each tab. A resource browser view allows you to select a scope: (All repos, selected repos, one repo, execution envs., file system and probably more later. The resource is then split in requirements and capabilities that can then be dragged/dropped. 

image

**Comment by pkriens** [comment]
Then the first tab is declaring the scope of the resolve/runtime.
image

**Comment by pkriens** [comment]
And then the resolver. 
image

**Comment by pkriens** [comment]
And last but not least the results
image

**Comment by pkriens** [comment]
The Balsamiq files are here: https://github.com/bndtools/bndtools/tree/master/bndtools.core/design

**Comment by BryanHunt** [comment]
While we are at it, could we get the ability to manipulate the -testpath as well?

Bryan

**Comment by bjhargrave** [comment]
How big a screen will we all need for those massive dialogs? :-)

**Comment by pkriens** [comment]
The layout is designed for 1000 px wide. This seems quite common though of course Eclipse eats a lot with margins. Of course we could make things collapsable but I often find that in the space of the collapsable header I would have preferred to see some content.

**Comment by wodencafe** [comment]
Wow cool, now that the week end is coming up I have some time to implement these new UIs!

**Comment by wodencafe** [comment]
@pkriens The **Resource Browser View**, should this be a standalone separate view (like the Repositories View), or attached to the existing pages?

**Comment by pkriens** [comment]
Both! I think you can develop it so that it is a separate view that tracks selected resources and/or can be used to find a specific resource. However, for the resolver I think it should be  glued to the right side because I expect you interact a lot with it. I know if the view is separate you can organize your window like that but if possible I think they should be really tied together.

**Comment by bjhargrave** [comment]
Closing. Please open a new PR if someone want to continue working on this.

**Pull request closed without merging**
