### PR TITLE
Update DS annotation option text to reflect 1.3

### PR DESCRIPTION
**Pull request by seanbright**
Not in love with this, but with 1.3 generally available it is a bit more
clear about capabilities.

Signed-off-by: Sean Bright <sean@malleable.com>

### CODE REVIEW

**Comment by bjhargrave** [comment]
In bnd 3.0, we changed the default for `-dsannotations` to be `*`. So you do not need to set `-dsannotations: *` in your bnd file anymore to get OSGi DS annotations processing. So I am not sure what the value of the UI is anymore.

Also, if we leave this UI, I don't care for `1.2+`. It would be better as simply `OSGi DS Annotations`.

**Comment by seanbright** [comment]
Does `-dsannotations: *` process both the bnd and the DS annotations? If not, we need the UI element to allow for people that don't want to update to the standard annotations.

**Comment by bjhargrave** [comment]
> Does -dsannotations: * process both the bnd and the DS annotations? 

No, just the OSGi DS annotations.

> If not, we need the UI element to allow for people that don't want to update to the standard annotations.

We want to nudge people off the bnd annotations. In the 3.0 release note, we announce the intention to deprecate the bnd annotations in a future release. So I am not sure how this will affect the UI.

**Comment by seanbright** [comment]
It's a minor change either way, so feel free to the close this PR if this isn't the direction you want to go.

**Comment by seanbright** [comment]
This a dead-end?

**Comment by seanbright** [comment]
Sorry to be a pest :grimacing:

**Comment by bjhargrave** [comment]
Squeaky wheel...

**Comment by seanbright** [comment]
Message received.

**Pull request merged**
