### PR TITLE
[builder] Define the order of the Eclipse build based on bnd order

### PR DESCRIPTION
**Pull request by pkriens**
Signed-off-by: Peter Kriens <peter.kriens@aqute.biz>

### CODE REVIEW

**Comment by fhuberts** [comment]
How about non-bnd projects in the workspace?

**Comment by dhumeniuk** [comment]
This change is giving me the following exception when building now:

    Caused by: java.lang.NullPointerException
	    at org.bndtools.builder.NewBuilder.isSame(NewBuilder.java:257)
	    at org.bndtools.builder.NewBuilder.setBuildOrder(NewBuilder.java:239)
	    at org.bndtools.builder.NewBuilder.build(NewBuilder.java:141)

**Comment by pkriens** [comment]
I did move the actual work to a branch to work out the kinks with some of the larger builds I know of. I've completely rewritten and broken up the builder since then. It looks awfully nice. Look at https://github.com/pkriens/bndtools/tree/launchremote

I've fixed this NPE for the current main build in 317c19a108a7925b149868ea8bfc8e05f5e93267

**Comment by dhumeniuk** [comment]
@pkriens is there an update site to use for your branch or what's the best way to check this out?

we have a fairly large build and the current builder in the master can be really slow whenever a change is made to an API project, would be great to see an improvement performance wise

**Comment by timothyjward** [comment]
@pkriens it would be great to get a build of your branch on the bndtools cloudbees. I'd set it up myself, but I'm not one of the Jenkins admins.

**Comment by pkriens** [comment]
Just check out my branch and run ./gradlew, then install in Eclipse from build/generated/p2

Works like a charm, actually better than I was hoping for :-)

BJ is now (supposed to) testing it on the OSGi build. If that works I will move it to Jenkins

**Comment by timothyjward** [comment]
Jenkins now has a build of the branch. It can be installed from:

https://bndtools.ci.cloudbees.com/job/pkriens.newBuilder/lastSuccessfulBuild/artifact/build/generated/p2/

using the "development build" instructions at:
http://bndtools.org/installation.html

**Comment by dhumeniuk** [comment]
Just saw the update site is above. Will check this out, but before I saw that I got this compiling error:

    /Users/dhumeniuk/git/bndtools/bndtools.core/src/bndtools/refactor/PkgRenameParticipant.java:55: error: cannot access IJavaElementMapper
        if (((RenamePackageProcessor) this.getProcessor()).getRenameSubpackages())
                                                          ^
    class file for org.eclipse.jdt.core.refactoring.IJavaElementMapper not found

My classpath is:

-classpath /Users/dhumeniuk/git/bndtools/cnf/buildrepo/osgi.core/osgi.core-4.3.1.jar:/Users/dhumeniuk/git/bndtools/cnf/buildrepo/osgi.cmpn/osgi.cmpn-4.3.1.jar:/Users/dhumeniuk/git/bndtools/cnf/cache/https%3A%2F%2Fbndtools.ci.cloudbees.com%2Fjob%2Fbnd.master%2FlastSuccessfulBuild%2Fartifact%2Fdist%2Fbundles%2Fbiz.aQute.bndlib/biz.aQute.bndlib-3.0.0.jar:/Users/dhumeniuk/git/bndtools/cnf/cache/https%3A%2F%2Fbndtools.ci.cloudbees.com%2Fjob%2Fbnd.master%2FlastSuccessfulBuild%2Fartifact%2Fdist%2Fbundles%2Fbiz.aQute.repository/biz.aQute.repository-3.0.0.jar:/Users/dhumeniuk/git/bndtools/cnf/cache/https%3A%2F%2Fbndtools.ci.cloudbees.com%2Fjob%2Fbnd.master%2FlastSuccessfulBuild%2Fartifact%2Fdist%2Fbundles%2Fbiz.aQute.resolve/biz.aQute.resolve-3.0.0.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.runtime_3.7.0.v20110110.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jface_3.7.0.v20110928-1505.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jface.text_3.7.2.v20111213-1208.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.resources_3.7.101.v20120125-1505.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.equinox.common_3.6.0.v20110523.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.swt.cocoa.macosx.x86_64_3.7.2.v3740f.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.swt_3.7.2.v3740f.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.text_3.5.101.v20110928-1504.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ui.workbench_3.7.1.v20120104-1859.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ui.ide_3.7.0.v20110928-1505.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.jobs_3.5.101.v20120113-1953.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.equinox.registry_3.5.101.R37x_v20110810-1611.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jdt.core_3.7.3.v20120119-1537.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jdt.ui_3.7.2.v20120109-1427.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.osgi_3.7.2.v20120110-1415.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.commands_3.6.0.I20110111-0800.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.team.core_3.6.0.I20110525-0800.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ui.forms_3.5.101.v20111011-1919.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ui.workbench.texteditor_3.7.0.v20110928-1504.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ui.editors_3.7.0.v20110928-1504.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ui.views_3.6.0.v20110928-1505.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.debug.core_3.7.1.v20111129-2031.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.debug.ui_3.7.102.v20111129-1423_r372.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jdt.launching_3.6.1.v20111006_r372.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jdt.debug.ui_3.6.1.v20111006_r372.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.jdt.junit_3.7.0.v20110928-1453.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.equinox.preferences_3.4.2.v20120111-2020.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.help.base_3.6.2.v201202080800.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ltk.core.refactoring_3.5.201.r372_v20111101-0700.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.ltk.ui.refactoring_3.6.0.v20110928-1453.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.filebuffers_3.5.200.v20110928-1504.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.expressions_3.4.300.v20110228.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.filesystem_1.3.100.v20110423-0524.jar:/Users/dhumeniuk/.bnd/cache/http%3A%2F%2Feclipse-repo-3.7.2.s3.amazonaws.com/org.eclipse.core.contenttype_3.4.100.v20110423-0524.jar:/Users/dhumeniuk/git/bndtools/cnf/buildrepo/javax.xml/javax.xml-1.3.4.jar:/Users/dhumeniuk/git/bndtools/cnf/buildrepo/javax.xml.stream/javax.xml.stream-1.0.1.jar:/Users/dhumeniuk/git/bndtools/cnf/buildrepo/osgi.r5/osgi.r5-1.0.1.jar:/Users/dhumeniuk/git/bndtools/bndtools.core/libs/org.osgi.service.obr-1.0.2.jar:/Users/dhumeniuk/git/bndtools/bndtools.core/libs/jcip-annotations.jar:/Users/dhumeniuk/git/bndtools/bndtools.api/generated/bndtools.api.jar:/Users/dhumeniuk/git/bndtools/org.bndtools.headless.build.manager/generated/org.bndtools.headless.build.manager.jar:/Users/dhumeniuk/git/bndtools/org.bndtools.versioncontrol.ignores.manager/generated/org.bndtools.versioncontrol.ignores.manager.jar:/Users/dhumeniuk/git/bndtools/bndtools.utils/bin:/Users/dhumeniuk/git/bndtools/bndtools.repository.base/generated/bndtools.repository.base.jar:/Users/dhumeniuk/git/bndtools/cnf/buildrepo/junit.osgi/junit.osgi-3.8.2.jar

**Comment by bjhargrave** [comment]
> I saw that I got this compiling error:
> 
> /Users/dhumeniuk/git/bndtools/bndtools.core/src/bndtools/refactor/PkgRenameParticipant.java:55: error: cannot access IJavaElementMapper
>     if (((RenamePackageProcessor) this.getProcessor()).getRenameSubpackages())
>                                                       ^
> class file for org.eclipse.jdt.core.refactoring.IJavaElementMapper not found

You must compile with JDK 7. This error occurs when compiling with JDK 8. See #959.

**Pull request merged**
