### PR TITLE
Fixes to New Project Wizard

### PR DESCRIPTION
**Pull request by seanbright**
Signed-off-by: Sean Bright <sean@malleable.com>

### CODE REVIEW

**Comment by seanbright** [comment]
Before and after:

image

**Comment by seanbright** [comment]
I've removed the call to `setFont()`

**Comment by bjhargrave** [comment]
You should squash that into the "rework project location" commit.

**Comment by bjhargrave** [comment]
LGTM. @pkriens, @njbartlett any concerns with merging?

**Comment by njbartlett** [comment]
Looks good. Merging.

**Comment by seanbright** [comment]
here's hoping that it looks good on macos :pray:

**Pull request merged**
