### PR TITLE
added shortcuts and liferay+jmx example

### PR DESCRIPTION
**Pull request by gamerson**
This requires https://github.com/bndtools/bnd/pull/909

### CODE REVIEW

**Comment by pkriens** [comment]
Could you change
1) the -runpath could be changed to biz.aQute.remote.launcher
2) Please rename to liferay.bndrun to remote.bndrun or something. Propose to add the different configs with macros as you already did?

**Comment by gamerson** [comment]
Sure thing, pushed new commit.

**Comment by gamerson** [comment]
@pkriens just pinging to see if we can get this merged, so the shortcuts will be available.  i'm using the remote/native launch alot and shortcuts would be handy.

**Comment by pkriens** [comment]
If you fix the PR to be mergeable, then I will pull it.

**Comment by gamerson** [comment]
Rebase and repushed.

**Pull request merged**
