### PR TITLE
For #1780 Added bndtools.pde project for plugin development using Bndtools

### PR DESCRIPTION
**Pull request by eliasvasylenko**
For #1780 

Might be a bit rough around the edges, but the only major things missing I think are icon decorations for borked target locations, and a listener on file moves to track run descriptors. Anyway I'll be away for about a week so I wanted to submit this for review in the meantime.

The new project contains two target location extensions for exposing Bnd
workspaces to PDE tooling:

- RepositoryTargetLocation allows adding the contents of Bnd
repositories to target definitions

- RunDescriptorTargetLocation allows adding -runbundles from a run
descriptor to a target definition.

I'm also open to suggestions for further Bnd/PDE integration ...

Signed-off-by: Elias N Vasylenko <eliasvasylenko@gmail.com>

### CODE REVIEW

**Comment by timothyjward** [comment]
I'm not a PDE expert, but it broadly looks fine to me from a code perspective. 

The only questions that I have are:

* Doesn't something need to be added to the p2 feature.xml to get the bundle installed?
* Should this be added as a separate feature, rather than an "always on" component? The M2E integration has https://github.com/bndtools/bndtools/blob/master/build/build.gradle#L170-L176 and https://github.com/bndtools/bndtools/blob/master/build/feature/bndtools-m2e/feature.xml to do this

It's probably best to do a rebase and force push now that we've moved to 4.0.0.DEV. A local build/install should also prove whether I'm correct about needing to update the feature definitions.

**Comment by timothyjward** [comment]
I've tried using this locally, and I get some issues when trying to do a test run. One of them is that the new plugin doesn't resolve. I've included a couple of review comments that should fix that bit.

I've also confirmed that the bndtools p2 repository that gets built doesn't install the new bndtools.pde code.

**Comment by eliasvasylenko** [comment]
Ah you're absolutely right, you even mentioned these things as I was getting started and I still ended up missing it! Oops. Thank you for taking a look at it, I'll make these changes as soon as I get a chance.

**Comment by eliasvasylenko** [comment]
CI hasn't finished yet but it appears to work now, including installing the new PDE feature locally into an existing eclipse installation. I just copied the m2e stuff for license information attached to the feature so I assume it's all kosher.

**Comment by timothyjward** [comment]
> CI hasn't finished yet but it appears to work now, including installing the new PDE feature locally into an existing eclipse installation. I just copied the m2e stuff for license information attached to the feature so I assume it's all kosher.

I can confirm that the install works, and that PDE integration appears as a selectable option. The installation didn't cause errors with either of my big workspaces so I'm happy for it to be merged. I don't do PDE development but it may be worth @peterkir taking a look at what (if anything) else could be added on top of this.

**Pull request merged**
