### PR TITLE
container: Properly initialize bnd class path container when requested

### PR DESCRIPTION
**Pull request by bjhargrave**
Fixes https://github.com/bndtools/bndtools/issues/1430

### CODE REVIEW

**Comment by gamerson** [comment]
It seems this change will have the chance to block the UI.  I've seen cases where eclipse wants to initialize classpath containers on the UI thread (like if the classpath container is open in Package Explorer on restart of Eclipse).  

But I have see the problem that #1430 talks about.  So we need to address this problem.  What about this?  After BndContainer is properly initialized, what if we serialize the classpath entries to a IMemento.  Then on restart of Eclipse, if Eclipse needs to initialize the BndContainer early before Workspace is ready (and possibly could be on the UI thread) we could initially restore the BndContainer from the IMemento serialization.  So 99% of the time the container would be "correct enough" to not cause tons of errors seen by #1430 and then once Workspace is ready, we do the "real init" of BndContainer and throw away the serialized entries.  

What do you think?  That would prevent the UI blocking of initing the workspace.

**Comment by bjhargrave** [comment]
> What do you think? That would prevent the UI blocking of initing the workspace.

Lets hold off for a little while. @pkriens has a replacement for FixedIndexRepo which will improve workspace startup time when there is no change to the index files. This is a source of time delay which, if ameliorated, will mean we really don't need to jump through a load of hoops to delay workspace init.

**Comment by gamerson** [comment]
@bjhargrave even if Peter fixes FixedIndexRepo, the problem I mentioned would still remain with MavenBndRepository which is the type of repo I've done all of my UI testing with.

**Comment by bjhargrave** [comment]
But I think it is fundamentally wrong to fake out the container until later. An IMemento approach is of little use if the file system changes outside of Eclipse (e.g. a git checkout of a different branch before starting Eclipse). The file system has the correct information, we need to use it to set the classpath container if Eclipse demands the classpath container be set on the UI thread. The better solution would be for Eclipse to not request to initialize the classpath container on the UI thread.

We should make bnd load projects as fast as possible to reduce the work needed to setup the classpath container but we should not set the classpath containers to false information.

**Comment by bjhargrave** [comment]
> After BndContainer is properly initialized, what if we serialize the classpath entries to a IMemento. Then on restart of Eclipse, if Eclipse needs to initialize the BndContainer early before Workspace is ready (and possibly could be on the UI thread) we could initially restore the BndContainer from the IMemento that was serialized earlier (before restart of eclipse).

@gamerson How would we do this? I poked around the eclipse API and could not see how a memento for the container/project can be obtained from the arguments passed to `BndContainerInitializer.initialize(IPath, IJavaProject)`. Mementos seem to be associated with UI elements and the classpath container is not a UI element.

**Comment by bjhargrave** [comment]
I am going to merge this for now. If we figure our a memento approach, we can make a new PR.

**Comment by gamerson** [comment]
@bjhargrave I was incorrect I don't think there is a built-in way to use IMemento.  I was just thinking we could use it manually use the eclipse Memento APIs if we wanted to serialize so its human readable, m2e guys just write a binary state file to serialize their container.

**Pull request merged**
